### ISSUE TITLE
Additional module for Tablet/Handy 

### ISSUE THREAD

**Issue by Neon82** [Smashman/table-map-foundryvtt-module#1]
It would be nice if you would programm a module inverted to this one. So player can login (via Tablet) but would only get the right navigation bar for Chat/CombatTracker/Charakter/Itmes/etc displayed and can open the elements in each navigation tab, like the Charakter sheets witch will then shown full screen on the tablet. if the close the char sheet the get back to the right navigation Bar.

**Comment by Smashman** [comment]
Interesting suggestion, though as it's not related to this module I'm going to close the issue.

I will keep it in mind as I have players that might also like this.

Thanks
