### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ducky00** [Smashman/table-map-foundryvtt-module#3]
This is not a request or bug report, just a question, sorry if this is not the right way to contact you on these regards. I just saw this module and I was wondering if it does virtually a similar thing as Stream Viewer but with Screen Size adaptation

**Comment by Smashman** [comment]
If you are referring to this module: https://foundryvtt.com/packages/stream-view

Then yes, it's somewhat similar. It doesn't have any tracking options, it simply scaled the map to the centre of the map, so I would recommend making a map the correct size for your screen. 

Hope that answers your question.
